### ISSUE TITLE
Test UI visiblities during player turn processes

### ISSUE THREAD

**Issue by LaytonGB** [UoS-CompSci-Team/Y2-S2-Software-Development-Project#81]
# Tasks

## End turn tests

End turn should always be hidden if:
- [ ] dice are not waiting to be rolled
- [ ] piece is not being placed
- [ ] robber is not awaiting movement
- [ ] player is not selecting a robber steal target

Cannot yet test:
- players are not discarding cards
- trade is not unconfirmed
- cannot go to next turn while in settings menu
- player is not selecting resource due to monopoly card usage
